### ISSUE TITLE
No directions as to how to actually get this extension installed in Visual Studio Code

### ISSUE THREAD

**Issue by dhorvathuofa** [owenrumney/yuck-vscode#2]
Downloaded this from git...then what? How do I actually get this extension loaded into vs code?

**Comment by owenrumney** [comment]
Generally installing through vscode as an extension or through the market place is easiest way to do this
https://marketplace.visualstudio.com/items?itemName=eww-yuck.yuck

![image](https://github.com/owenrumney/yuck-vscode/assets/3049157/c969599a-100c-40ee-a449-aa3a34c54f84)
